apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: nirmalazpipeline 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nirmalazpipeline 
    spec:
      containers:
        - name: nirmalazpipeline 
          image: nirmalregistry.azurecr.io/nirmalazpipeline
          ports:
          - containerPort: 8081